# BINDIR is the directory where the moria binary will be put
# LIBDIR is where the other files (score, news, hours) will be put
# LIBDIR must be the same directory defined in config.h
BINDIR = C:/umoria
LIBDIR = C:/umoria/data

# Game binary name. e.g `moria` or `umoria`.
TARGET = umoria

# Custom include paths. e.g. ncurses includes for MinGW on Windows.
INC = -I/usr/include/ncurses/

# For testing and debugging the program, it is best to use this line.
CFLAGS = -g -Wall -std=gnu11 $(INC)

# For playing the game, you may want to use this line
# CFLAGS = -O
# NOTE: the -O flag currently crashes the game when running! -- MRC (2016-09-30)

# Required for GCC compilation under MinGW
PTHREAD = -static -lpthread

CURSES = -lncurses

LFLAGS =

# GCC is required when using MinGW
CC = gcc

SRCS = main.c misc1.c misc2.c misc3.c misc4.c store1.c files.c io.c \
	create.c desc.c generate.c sets.c dungeon.c creature.c death.c \
	eat.c help.c magic.c potions.c prayer.c save.c staffs.c wands.c \
	scrolls.c spells.c wizard.c store2.c stats.c str_insert.c inventory.c \
	progress.c score_death.c save_state.c player_pos.c hp_table.c \
	player_light.c burden.c spells_known.c object_levels.c \
	missile_serial.c inven_command_state.c screen_touched.c \
	level_exit.c pending_teleport.c input_ended.c running.c \
	command_state.c player_gold.c player_food.c player_display_numbers.c \
	player_mana.c player_hp.c player_level.c player_status_flags.c \
	player_abilities.c player_timed_effects.c player_resting.c \
	player_speed.c player_infra_range.c player_glowing_hands.c \
	player_spells_to_learn.c player_max_depth.c player_hit_die.c player_armour_class.c player_base_to_hit.c \
	player_disarm.c player_saving_throw.c player_race.c \
	moria1.c moria2.c \
	moria3.c moria4.c monsters.c treasure.c variable.c rnd.c recall.c \
	player.c tables.c

OBJS = main.o misc1.o misc2.o misc3.o misc4.o store1.o files.o io.o \
	create.o desc.o generate.o sets.o dungeon.o creature.o death.o \
	eat.o help.o magic.o potions.o prayer.o save.o staffs.o wands.o \
	scrolls.o spells.o wizard.o store2.o stats.o str_insert.o inventory.o \
	progress.o score_death.o save_state.o player_pos.o hp_table.o \
	player_light.o burden.o spells_known.o object_levels.o \
	missile_serial.o inven_command_state.o screen_touched.o \
	level_exit.o pending_teleport.o input_ended.o running.o \
	command_state.o player_gold.o player_food.o player_display_numbers.o \
	player_mana.o player_hp.o player_level.o player_status_flags.o \
	player_abilities.o player_timed_effects.o player_resting.o \
	player_speed.o player_infra_range.o player_glowing_hands.o \
	player_spells_to_learn.o player_max_depth.o player_hit_die.o player_armour_class.o player_base_to_hit.o \
	player_disarm.o player_saving_throw.o player_race.o \
	moria1.o moria2.o \
	moria3.o moria4.o monsters.o treasure.o variable.o rnd.o recall.o \
	player.o tables.o

LIBFILES = splash.hlp origcmds.hlp owizcmds.hlp roglcmds.hlp \
			rwizcmds.hlp version.hlp welcome.hlp

DOCS = manual.md

moria : $(OBJS)
	$(CC) -o $(TARGET) $(CFLAGS) $(OBJS) $(CURSES) $(PTHREAD) $(LFLAGS)

# you must define BINDIR and LIBDIR before installing
# assumes that BINDIR and LIBDIR exist
install:
	mkdir -p $(BINDIR)
	chmod 755 $(BINDIR)
	cp -f $(TARGET) $(BINDIR)/$(TARGET)
	chmod 4711 $(BINDIR)/$(TARGET)
	mkdir -p $(LIBDIR)
	chmod 711 $(LIBDIR)
	cp -f ../LICENSE $(BINDIR)
	(cd ../data; cp -f $(LIBFILES) $(LIBDIR))
	(cd ../docs; cp -f $(DOCS) $(BINDIR))
	(cd $(LIBDIR); chmod 444 $(LIBFILES))
	(cd $(BINDIR); touch scores.dat; chmod 644 scores.dat)
# If you are short on disk space, or aren't interested in debugging moria.
#	strip $(BINDIR)/moria

clean:
	@rm -r $(OBJS)
	@rm -f $(TARGET)
	@echo "Compilation files removed!"

burden.o: burden.h constant.h types.h config.h
command_state.o: command_state.h constant.h types.h config.h
create.o: constant.h types.h externs.h config.h
creature.o: constant.h types.h externs.h config.h
death.o: constant.h types.h externs.h config.h
desc.o: constant.h types.h externs.h config.h
dungeon.o: constant.h types.h externs.h config.h
eat.o: constant.h types.h externs.h config.h
files.o: constant.h types.h externs.h config.h
generate.o: constant.h types.h externs.h config.h
help.o: constant.h types.h externs.h config.h
hp_table.o: hp_table.h constant.h types.h config.h
inventory.o: inventory.h equipment.h constant.h types.h config.h
io.o: constant.h types.h externs.h config.h
magic.o: constant.h types.h externs.h config.h
main.o: constant.h types.h externs.h config.h
misc1.o: constant.h types.h externs.h config.h
misc2.o: constant.h types.h externs.h config.h
misc3.o: burden.h constant.h types.h externs.h config.h
misc4.o: constant.h types.h externs.h config.h
missile_serial.o: missile_serial.h constant.h types.h config.h
level_exit.o: level_exit.h constant.h types.h config.h
pending_teleport.o: pending_teleport.h constant.h types.h config.h
input_ended.o: input_ended.h constant.h types.h config.h
running.o: running.h constant.h types.h config.h
inven_command_state.o: inven_command_state.h screen_touched.h constant.h types.h config.h
screen_touched.o: screen_touched.h constant.h types.h config.h
monsters.o: constant.h types.h config.h
object_levels.o: object_levels.h constant.h types.h config.h
moria1.o: burden.h constant.h types.h externs.h config.h
moria2.o: constant.h types.h externs.h config.h
moria3.o: constant.h types.h externs.h config.h
moria4.o: burden.h constant.h types.h externs.h config.h
player.o: constant.h types.h config.h
player_abilities.o: player_abilities.h constant.h types.h config.h
player_display_numbers.o: player_display_numbers.h constant.h types.h config.h
player_food.o: player_food.h constant.h types.h config.h
player_gold.o: player_gold.h constant.h types.h config.h
player_light.o: player_light.h constant.h types.h config.h
player_hp.o: player_hp.h constant.h types.h config.h
player_level.o: player_level.h constant.h types.h config.h
player_mana.o: player_mana.h constant.h types.h config.h
player_pos.o: player_pos.h constant.h types.h config.h
player_status_flags.o: player_status_flags.h constant.h types.h config.h
# The only one of these modules that calls another: the eighteen clocks ask
# player_status_flags.c to set and clear the twelve marks that pair with them.
player_timed_effects.o: player_timed_effects.h player_status_flags.h constant.h types.h config.h
player_resting.o: player_resting.h constant.h types.h config.h
player_speed.o: player_speed.h constant.h types.h config.h
player_infra_range.o: player_infra_range.h constant.h types.h config.h
player_glowing_hands.o: player_glowing_hands.h constant.h types.h config.h
player_spells_to_learn.o: player_spells_to_learn.h constant.h types.h config.h
player_max_depth.o: player_max_depth.h constant.h types.h config.h
player_hit_die.o: player_hit_die.h constant.h types.h config.h
player_armour_class.o: player_armour_class.h constant.h types.h config.h
player_base_to_hit.o: player_base_to_hit.h constant.h types.h config.h
player_disarm.o: player_disarm.h constant.h types.h config.h
player_saving_throw.o: player_saving_throw.h constant.h types.h config.h
player_race.o: player_race.h constant.h types.h config.h
potions.o: constant.h types.h externs.h config.h
prayer.o: constant.h types.h externs.h config.h
progress.o: progress.h constant.h types.h config.h
recall.o: constant.h config.h types.h externs.h
rnd.o: constant.h types.h
save.o: burden.h constant.h types.h externs.h config.h
save_state.o: save_state.h progress.h score_death.h constant.h types.h config.h
score_death.o: score_death.h constant.h types.h config.h
scrolls.o: constant.h types.h externs.h config.h
sets.o: constant.h config.h
spells.o: constant.h types.h externs.h config.h
spells_known.o: spells_known.h constant.h types.h config.h
staffs.o: constant.h types.h externs.h config.h
store1.o: constant.h types.h externs.h config.h
store2.o: constant.h types.h externs.h config.h
stats.o: stats.h constant.h types.h config.h
str_insert.o: str_insert.h constant.h types.h config.h
tables.o: constant.h types.h config.h
treasure.o: constant.h types.h config.h
variable.o: constant.h types.h config.h
wands.o: constant.h types.h externs.h config.h
wizard.o: constant.h types.h externs.h config.h
