# BINDIR is the directory where the moria binary will be put
# LIBDIR is where the other files (score, news, hours) will be put
# LIBDIR must be the same directory defined in config.h
BINDIR = C:/umoria
LIBDIR = C:/umoria/data

# Game binary name. e.g `moria` or `umoria`.
TARGET = umoria

# Custom include paths. e.g. ncurses includes for MinGW on Windows.
INC = -I/usr/include/ncurses/

# For testing and debugging the program, it is best to use this line.
CFLAGS = -g -Wall -std=gnu11 $(INC)

# For playing the game, you may want to use this line
# CFLAGS = -O
# NOTE: the -O flag currently crashes the game when running! -- MRC (2016-09-30)

# Required for GCC compilation under MinGW
PTHREAD = -static -lpthread

CURSES = -lncurses

LFLAGS =

# GCC is required when using MinGW
CC = gcc

# src/ の .c の一覧は根の sources.mk に 1 つだけ書く（makefile が読むのと
# 同じもの）。このファイルは src/ の中で動かす前提（下の依存行が src/ からの
# 相対の名前で書いてある）なので、sources.mk はこのファイルの置き場から探す。
include $(dir $(lastword $(MAKEFILE_LIST)))sources.mk

OBJS = $(SRCS:.c=.o)

LIBFILES = splash.hlp origcmds.hlp owizcmds.hlp roglcmds.hlp \
			rwizcmds.hlp version.hlp welcome.hlp

DOCS = manual.md

moria : $(OBJS)
	$(CC) -o $(TARGET) $(CFLAGS) $(OBJS) $(CURSES) $(PTHREAD) $(LFLAGS)

# you must define BINDIR and LIBDIR before installing
# assumes that BINDIR and LIBDIR exist
install:
	mkdir -p $(BINDIR)
	chmod 755 $(BINDIR)
	cp -f $(TARGET) $(BINDIR)/$(TARGET)
	chmod 4711 $(BINDIR)/$(TARGET)
	mkdir -p $(LIBDIR)
	chmod 711 $(LIBDIR)
	cp -f ../LICENSE $(BINDIR)
	(cd ../data; cp -f $(LIBFILES) $(LIBDIR))
	(cd ../docs; cp -f $(DOCS) $(BINDIR))
	(cd $(LIBDIR); chmod 444 $(LIBFILES))
	(cd $(BINDIR); touch scores.dat; chmod 644 scores.dat)
# If you are short on disk space, or aren't interested in debugging moria.
#	strip $(BINDIR)/moria

clean:
	@rm -r $(OBJS)
	@rm -f $(TARGET)
	@echo "Compilation files removed!"

abilities.o: abilities.h constant.h types.h externs.h config.h
burden.o: burden.h constant.h types.h config.h
command_state.o: command_state.h constant.h types.h config.h
create.o: constant.h types.h externs.h config.h
creature.o: constant.h types.h externs.h config.h
death.o: constant.h types.h externs.h config.h
desc.o: constant.h types.h externs.h config.h
device.o: device.h constant.h types.h externs.h config.h
dungeon.o: constant.h types.h externs.h config.h
eat.o: constant.h types.h externs.h config.h
files.o: constant.h types.h externs.h config.h
game_state.o: game_state.h burden.h constant.h types.h externs.h config.h
generate.o: constant.h types.h externs.h config.h
help.o: constant.h types.h externs.h config.h
hp_table.o: hp_table.h constant.h types.h config.h
input.o: input.h
input_ncurses.o: input.h backend_ncurses.h
inventory.o: inventory.h equipment.h constant.h types.h config.h
io.o: constant.h types.h externs.h config.h
item_ident.o: item_ident.h constant.h types.h externs.h config.h
magic.o: constant.h types.h externs.h config.h
main.o: constant.h types.h externs.h config.h
messages.o: messages.h constant.h types.h externs.h config.h
misc1.o: constant.h types.h externs.h config.h
misc2.o: constant.h types.h externs.h config.h
misc3.o: burden.h constant.h types.h externs.h config.h
misc4.o: constant.h types.h externs.h config.h
missile_serial.o: missile_serial.h constant.h types.h config.h
level_exit.o: level_exit.h constant.h types.h config.h
options.o: options.h constant.h types.h externs.h config.h
panel.o: panel.h constant.h types.h externs.h config.h
pending_teleport.o: pending_teleport.h constant.h types.h config.h
input_ended.o: input_ended.h constant.h types.h config.h
platform.o: platform.h backend_ncurses.h render.h input.h
render.o: render.h
render_ncurses.o: render.h backend_ncurses.h
running.o: running.h constant.h types.h config.h
inven_command_state.o: inven_command_state.h screen_touched.h constant.h types.h config.h
screen_touched.o: screen_touched.h constant.h types.h config.h
monsters.o: constant.h types.h config.h
object_levels.o: object_levels.h constant.h types.h config.h
moria1.o: burden.h constant.h types.h externs.h config.h
moria2.o: constant.h types.h externs.h config.h
moria3.o: constant.h types.h externs.h config.h
moria4.o: burden.h constant.h types.h externs.h config.h
player.o: constant.h types.h config.h
player_abilities.o: player_abilities.h constant.h types.h config.h
player_display_numbers.o: player_display_numbers.h constant.h types.h config.h
player_food.o: player_food.h constant.h types.h config.h
player_gold.o: player_gold.h constant.h types.h config.h
player_light.o: player_light.h constant.h types.h config.h
player_hp.o: player_hp.h constant.h types.h config.h
player_level.o: player_level.h constant.h types.h config.h
player_mana.o: player_mana.h constant.h types.h config.h
player_pos.o: player_pos.h constant.h types.h config.h
player_status_flags.o: player_status_flags.h constant.h types.h config.h
# The only one of these modules that calls another: the eighteen clocks ask
# player_status_flags.c to set and clear the twelve marks that pair with them.
player_timed_effects.o: player_timed_effects.h player_status_flags.h constant.h types.h config.h
player_resting.o: player_resting.h constant.h types.h config.h
player_speed.o: player_speed.h constant.h types.h config.h
player_infra_range.o: player_infra_range.h constant.h types.h config.h
player_glowing_hands.o: player_glowing_hands.h constant.h types.h config.h
player_spells_to_learn.o: player_spells_to_learn.h constant.h types.h config.h
player_max_depth.o: player_max_depth.h constant.h types.h config.h
player_hit_die.o: player_hit_die.h constant.h types.h config.h
player_armour_class.o: player_armour_class.h constant.h types.h config.h
player_base_to_hit.o: player_base_to_hit.h constant.h types.h config.h
player_disarm.o: player_disarm.h constant.h types.h config.h
player_saving_throw.o: player_saving_throw.h constant.h types.h config.h
player_race.o: player_race.h constant.h types.h config.h
player_body_weight.o: player_body_weight.h constant.h types.h config.h
player_attack_bonuses.o: player_attack_bonuses.h constant.h types.h config.h
player_search_skill.o: player_search_skill.h constant.h types.h config.h
player_bio.o: player_bio.h constant.h types.h config.h
player_stealth.o: player_stealth.h constant.h types.h config.h
player_class.o: player_class.h constant.h types.h config.h
monster_turn.o: monster_turn.h constant.h types.h config.h
monster_levels.o: monster_levels.h constant.h types.h config.h
monster_breeding.o: monster_breeding.h constant.h types.h config.h
monster_list.o: monster_list.h constant.h types.h config.h
dungeon_size.o: dungeon_size.h
dungeon_level.o: dungeon_level.h
floor_items.o: floor_items.h constant.h types.h config.h
dungeon_map.o: dungeon_map.h constant.h types.h config.h
potions.o: constant.h types.h externs.h config.h
prayer.o: constant.h types.h externs.h config.h
progress.o: progress.h constant.h types.h config.h
recall.o: constant.h config.h types.h externs.h
rnd.o: constant.h types.h
save.o: burden.h constant.h types.h externs.h config.h
save_state.o: save_state.h progress.h score_death.h constant.h types.h config.h
score_death.o: score_death.h constant.h types.h config.h
scrolls.o: constant.h types.h externs.h config.h
sets.o: constant.h config.h
signal_flags.o: signal_flags.h
signals.o: constant.h types.h externs.h config.h signal_flags.h
spells.o: constant.h types.h externs.h config.h
spells_known.o: spells_known.h constant.h types.h config.h
staffs.o: constant.h types.h externs.h config.h
store1.o: constant.h types.h externs.h config.h
store2.o: constant.h types.h externs.h config.h
stats.o: stats.h constant.h types.h config.h
stores.o: stores.h constant.h types.h externs.h config.h
str_insert.o: str_insert.h constant.h types.h config.h
tables.o: constant.h types.h config.h
treasure.o: constant.h types.h config.h
variable.o: constant.h types.h config.h
view_observer.o: view_observer.h
wands.o: constant.h types.h externs.h config.h
wizard.o: constant.h types.h externs.h config.h
